name: Generate Documentation

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 2 days at midnight UTC
  push:
    branches:
      - main
      - repomix
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DOCS_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Repomix
        run: npm install -g repomix

      - name: Generate WAVS Foundry Template Documentation
        run: repomix --remote Lay3rLabs/wavs-foundry-template -o public/wavs-foundry-template.md --style markdown

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Generate Rust Crate Documentation
        run: |
          # Clone the wavs-wasi repo using the token
          git clone https://${{ secrets.DOCS_PAT }}@github.com/Lay3rLabs/wavs-wasi.git
          cd wavs-wasi/packages/wavs-wasi-utils

          # Build the docs
          echo "Building docs with cargo..."
          cargo doc --no-deps

          # Create temporary directory for markdown files
          TEMP_DIR=$(mktemp -d)
          echo "Created temp directory: $TEMP_DIR"

          # Convert and concatenate Markdown
          DOC_DIR="../../target/doc/wavs_wasi_utils"
          echo "Converting HTML docs to Markdown..."

          find "$DOC_DIR" -name "*.html" | sort | while read -r html_file; do
            echo "Processing: $html_file"
            clean_name=$(basename "$html_file" .html | sed 's/fn\.//' | sed 's/macro\.//')
            md_file="$TEMP_DIR/$clean_name.md"
            if [[ "$html_file" == *"/fn."* ]]; then
              echo "## Function: $clean_name" > "$md_file"
            elif [[ "$html_file" == *"/macro."* ]]; then
              echo "## Macro: $clean_name" > "$md_file"
            elif [[ "$html_file" == *"/index.html" ]]; then
              echo "# Module: $(dirname "$html_file" | xargs basename)" > "$md_file"
            else
              echo "## $clean_name" > "$md_file"
            fi
            echo "" >> "$md_file"
            pandoc "$html_file" -f html -t markdown --wrap=none >> "$md_file"
          done

          # Concatenate all markdown files
          echo "Concatenating Markdown files..."
          cat "$TEMP_DIR"/*.md > ../../../public/wavs-wasi-utils.md

          # Clean up
          cd ../../..
          rm -rf wavs-wasi "$TEMP_DIR"

      - name: Generate wavs-types Documentation
        run: |
          # Clone the wavs-types repo using the token
          git clone https://${{ secrets.DOCS_PAT }}@github.com/Lay3rLabs/wavs-types.git
          cd wavs-types

          # Build the docs
          echo "Building docs with cargo..."
          cargo doc --no-deps

          # Create temporary directory for markdown files
          TEMP_DIR=$(mktemp -d)
          echo "Created temp directory: $TEMP_DIR"

          # Convert and concatenate Markdown
          DOC_DIR="target/doc/wavs_types"
          echo "Converting HTML docs to Markdown..."

          find "$DOC_DIR" -name "*.html" | sort | while read -r html_file; do
            echo "Processing: $html_file"
            clean_name=$(basename "$html_file" .html | sed 's/fn\.//' | sed 's/macro\.//')
            md_file="$TEMP_DIR/$clean_name.md"
            if [[ "$html_file" == *"/fn."* ]]; then
              echo "## Function: $clean_name" > "$md_file"
            elif [[ "$html_file" == *"/macro."* ]]; then
              echo "## Macro: $clean_name" > "$md_file"
            elif [[ "$html_file" == *"/index.html" ]]; then
              echo "# Module: $(dirname "$html_file" | xargs basename)" > "$md_file"
            else
              echo "## $clean_name" > "$md_file"
            fi
            echo "" >> "$md_file"
            pandoc "$html_file" -f html -t markdown --wrap=none >> "$md_file"
          done

          # Concatenate all markdown files
          echo "Concatenating Markdown files..."
          cat "$TEMP_DIR"/*.md > ../public/wavs-types.md

          # Clean up
          cd ..
          rm -rf wavs-types "$TEMP_DIR"

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/wavs-foundry-template.md public/wavs-wasi-utils.md public/wavs-types.md
          git commit -m "Update documentation" || exit 0
          git push
