name: Generate Documentation

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 2 days at midnight UTC
  push:
    branches:
      - main
      - repomix
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DOCS_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Repomix
        run: npm install -g repomix

      - name: Generate WAVS Foundry Template Documentation
        run: repomix --remote Lay3rLabs/wavs-foundry-template -o public/wavs-foundry-template.md --style markdown

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Install rustdoc-md
        run: cargo install rustdoc-md

      - name: Generate Rust Crate Documentation
        run: |
          # Clone the wavs-wasi repo using the token
          git clone https://${{ secrets.DOCS_PAT }}@github.com/Lay3rLabs/wavs-wasi.git
          cd wavs-wasi

          # Generate rustdoc JSON for wavs-wasi-utils
          echo "Generating rustdoc JSON for wavs-wasi-utils..."
          cd packages/wavs-wasi-utils
          RUSTC_BOOTSTRAP=1 RUSTDOCFLAGS="-Z unstable-options --output-format json" cargo doc --document-private-items --no-deps

          # Convert to Markdown
          if [ -f "target/doc/wavs_wasi_utils.json" ]; then
            rustdoc-md --path target/doc/wavs_wasi_utils.json --output ../../../public/wavs-wasi-utils.md
          else
            echo "wavs_wasi_utils.json not found."
            exit 1
          fi

          # Clean up wavs-wasi
          cd ../../..
          rm -rf wavs-wasi

          # # Clone the wavs-foundry-template repo
          # git clone https://${{ secrets.DOCS_PAT }}@github.com/Lay3rLabs/wavs-foundry-template.git
          # cd wavs-foundry-template

          # # Generate rustdoc JSON for evm-price-oracle
          # echo "Generating rustdoc JSON for evm-price-oracle..."
          # cd components/evm-price-oracle
          # RUSTC_BOOTSTRAP=1 RUSTDOCFLAGS="-Z unstable-options --output-format json" cargo doc --document-private-items --no-deps

          # # Convert to Markdown
          # if [ -f "target/doc/evm_price_oracle.json" ]; then
          #   rustdoc-md --path target/doc/evm_price_oracle.json --output ../../../public/evm-price-oracle.md
          # else
          #   echo "evm_price_oracle.json not found."
          #   exit 1
          # fi

          # # Clean up wavs-foundry-template
          # cd ../../..
          # rm -rf wavs-foundry-template

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/wavs-foundry-template.md public/wavs-wasi-utils.md
          git commit -m "Update documentation" || exit 0
          git push
