name: Generate Documentation

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 2 days at midnight UTC
  push:
    branches:
      - main
      - repomix
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DOCS_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Repomix
        run: npm install -g repomix

      - name: Generate WAVS Foundry Template Documentation
        run: repomix --remote Lay3rLabs/wavs-foundry-template -o public/wavs-foundry-template.md --style markdown

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Generate Rust Crate Documentation
        run: |
          # Clone the wavs-wasi repo using the token
          git clone https://${{ secrets.DOCS_PAT }}@github.com/Lay3rLabs/wavs-wasi.git
          cd wavs-wasi/packages/wavs-wasi-utils
          
          # Generate HTML docs with all items
          RUSTDOCFLAGS="--document-private-items" cargo doc --no-deps
          
          # Create a temporary file with the HTML content
          cat ../../target/doc/wavs_wasi_utils/index.html > ../../../temp_docs.html
          
          # Convert to markdown using pandoc
          cd ../../..
          pandoc temp_docs.html -f html -t markdown -o public/wavs-wasi-utils.md
          
          # Clean up
          rm -rf wavs-wasi temp_docs.html

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/wavs-foundry-template.md public/wavs-wasi-utils.md
          git commit -m "Update documentation" || exit 0
          git push
